const NaverActionTypes = {
  FETCH_NAVERS_START: "FETCH_NAVERS_START",
  FETCH_NAVERS_SUCCESS: "FETCH_NAVERS_SUCCESS",
  FETCH_NAVERS_FAILURE: "FETCH_NAVERS_FAILURE",
  FETCH_NAVER_DETAIL_START: "FETCH_NAVER_DETAIL_START",
  FETCH_NAVER_DETAIL_SUCCESS: "FETCH_NAVER_DETAIL_SUCCESS",
  FETCH_NAVER_DETAIL_FAILURE: "FETCH_NAVER_DETAIL_FAILURE",
  POST_NAVER_START: "POST_NAVER_START",
  POST_NAVER_SUCCESS: "POST_NAVER_SUCCESS",
  POST_NAVER_FAILURE: "POST_NAVER_FAILURE",
  PUT_NAVER_START: "PUT_NAVER_START",
  PUT_NAVER_SUCCESS: "PUT_NAVER_SUCCESS",
  PUT_NAVER_FAILURE: "PUT_NAVER_FAILURE",
  DELETE_NAVER_START: "DELETE_NAVER_START",
  DELETE_NAVER_SUCCESS: "DELETE_NAVER_SUCCESS",
  DELETE_NAVER_FAILURE: "DELETE_NAVER_FAILURE",
}

export default NaverActionTypes
