const NaverActionTypes = {
  FETCH_NAVERS_START: "FETCH_NAVERS_START",
  FETCH_NAVERS_SUCCESS: "FETCH_NAVERS_SUCCESS",
  FETCH_NAVERS_FAILURE: "FETCH_NAVERS_FAILURE",
}

export default NaverActionTypes
