const DialogActionTypes = {
  TOGGLE_TRIP_DIALOG: "TOGGLE_TRIP_DIALOG",
  TOGGLE_NAVER_DELETE_DIALOG: "TOGGLE_NAVER_DELETE_DIALOG",
  TOGGLE_NAVER_DETAIL_DIALOG: "TOGGLE_NAVER_DETAIL_DIALOG",
  TOGGLE_NAVER_FEEDBACK_DIALOG: "TOGGLE_NAVER_FEEDBACK_DIALOG",
}

export default DialogActionTypes
